module.exports = {
  NUM_TIMES_COMPOUNDED_PER_UNIT_TIME: 12,
  FEDERAL_TAX_BRACKET_TIER_1: 50197,
  // rent vs buy constants
  CLOSING_COST_PERCENTAGE_BUYING: 0.04,
  CLOSING_COST_PERCENTAGE_SELLING: 0.06,
  // https://www.youtube.com/watch?v=Uwl3-jBNEd4
  ESTIMATED_ANNUAL_PROPERTY_TAX_RATE: 0.01,
  ESTIMATED_ANNUAL_MAINTENANCE_COSTS_PERCENT: 0.01, // multiply by property value per year
  TOTAL_MORTGAGE_INTEREST_COST: 0.03,
  ESTIMATED_HOME_PRICE_GROWTH_RATE: 0.03,
  ESTIMATED_STOCKS_GROWTH_RATE: 0.0657,
};
